version: "3.5"
services:
  dind:
    image: docker:dind
    container_name: dind
    restart: unless-stopped
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - dind-certs-ca:/certs/ca
      - dind-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    command: ["--storage-driver=overlay2"]
    networks:
      devops:
        aliases:
          - docker

  gitea:
    image: gitea/gitea:latest-rootless
    container_name: gitea
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - gitea-data:/var/lib/gitea
      - ./gitea:/etc/gitea
    ports:
      - "8180:3000"
      - "8122:2222"
    networks:
      devops:
        aliases:
          - gitea

  jenkins:
    build:
      context: ./jenkins
      dockerfile: jenkins.dockerfile
    container_name: jenkins
    restart: unless-stopped
    environment:
      # Docker(DinD) Connection
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
      # Resolvendo o problema do plugin 'HTML Publisher'
      JAVA_OPTS: -Dhudson.model.DirectoryBrowserSupport.CSP="script-src 'unsafe-inline'"
    volumes:
      - dind-certs-ca:/certs/ca:ro
      - dind-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    ports:
      - "8280:8080"
      - "8250:50000"
    networks:
      - devops

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    restart: unless-stopped
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_WEB_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.2.jar=web"
      SONAR_CE_JAVAADDITIONALOPTS: "-javaagent:./extensions/plugins/sonarqube-community-branch-plugin-1.8.2.jar=ce"
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
      # Plugins do SonarQube
      - ./sonarqube/plugins:/opt/sonarqube/extensions/plugins
    ports:
      - "8380:9000"
    shm_size: "256M"
    networks:
      devops:
        aliases:
          - sonarqube

volumes:
  dind-certs-ca: {}
  dind-certs-client: {}
  gitea-data: {}
  jenkins-data: {}
  sonarqube-conf: {}
  sonarqube-data: {}
  sonarqube-extensions: {}
  sonarqube-logs: {}

networks:
  devops:
    external: false
